### ISSUE TITLE
Limit line count

### ISSUE THREAD

**Issue by FinalAngel** [aldryn/aldryn-boilerplate-bootstrap3#110]
https://github.com/aldryn/aldryn-boilerplate-bootstrap3/blob/master/.editorconfig#L12 to 80 in general

**Comment by intellectronica** [comment]
+1

**Comment by vxsx** [comment]
do you want to update .jscsrc as well to lint 80 chars per line?
it's going to be pretty painful for editors where editorconfig actually enforces this rule automatically
e.g. html files

**Comment by FinalAngel** [comment]
use 80 lines for all but 120 line for html

**Comment by vxsx** [comment]
question about jscsrc still stands. if we are to force 80 through linting - major refactoring incoming everywhere, if not then it doesn't make much sense, someone would surely complain that the line is 100 chars long when the linter says all green

**Comment by FinalAngel** [comment]
yeah the other variant would be to use 120 lines generally but force 80 for python?

**Comment by vxsx** [comment]
or limit all to 80 but js and html 120 :)

**Comment by vxsx** [comment]
i suddenly realized why some people love 2 spaces in javascript, haha

**Comment by intellectronica** [comment]
I also think 2 spaces in JS is appropriate, because JS code typically nests a lot. Not sure it's worth changing, since everyone got used to 4 spaces here. I don't think we should compromise on 80 columns, though - it's much easier to read.

**Comment by FinalAngel** [comment]
80 columns is fine, we should keep the 4 spaces to avoid confusion in general (thats also why we moved from tabs to spaces) so everyone (including python) can use 4 spaces no matter the editor.
