### ISSUE TITLE
Refactor content integration

### ISSUE THREAD

**Issue by FinalAngel** [aldryn/aldryn-boilerplate-bootstrap3#112]
we probably need to remove ``<div class="container">``in base.html as this causes issues on the addons. Container should be re-added in `fullwidth.html` and `sidebar_*.html`.

**Comment by vxsx** [comment]
:-1: putting in a container should be users decision imo. when you have a container in base you won't be able to do fullwidth sections without dirty hacks and weird css

**Comment by FinalAngel** [comment]
yes so this issue should remove that again for 4.0 @vxsx I adapted the description accordingly.

**Comment by vxsx** [comment]
i'm lost

**Comment by FinalAngel** [comment]
Will open a PR later and refer to it @vxsx :)
