### ISSUE TITLE
Documentation versions

### ISSUE THREAD

**Issue by FinalAngel** [aldryn/aldryn-boilerplate-bootstrap3#133]
Add capability of versioning the read the docs version:

![image](https://cloud.githubusercontent.com/assets/270307/9854097/515d9658-5b07-11e5-802f-74c5d3a060fb.png)

**Comment by vxsx** [comment]
<img width="323" alt="screen shot 2015-09-14 at 21 36 23" src="https://cloud.githubusercontent.com/assets/366813/9859817/acf3c1ce-5b28-11e5-8ea8-0f51855c2c95.png">

fixed
