### ISSUE TITLE
remove the "divio debug menu"

### ISSUE THREAD

**Issue by stefanfoulis** [aldryn/aldryn-boilerplate-bootstrap3#144]
I don't think it is something that makes sense to be displayed for every user of the stage site. It is rather confusing.

If it is really needed for development, how about removing it, and allowing to display it by entering something in the js console or so.

**Comment by vxsx** [comment]
:+1: for removing it, @FinalAngel ?

**Comment by FinalAngel** [comment]
that actually has been removed @vxsx in 4.x?

**Comment by vxsx** [comment]
oh lol, in fact in 3.4.0 https://github.com/aldryn/aldryn-boilerplate-bootstrap3/blob/master/CHANGELOG.rst#340
