### ISSUE TITLE
No documentation for 24-column Bootstrap grid

### ISSUE THREAD

**Issue by johnfraney** [aldryn/aldryn-boilerplate-bootstrap3#167]
This boilerplate uses a 24-column Bootstrap grid instead of the default 12-column grid (defined in `private/sass/settings/_bootstrap.scss:347`).

It would be helpful to document significant changes to default Bootstrap settings like this.

**Comment by vxsx** [comment]
Should be fixed with #168

**Comment by johnfraney** [comment]
Looks good!
