### ISSUE TITLE
Update to bootstrap 4

### ISSUE THREAD

**Issue by Llanilek** [aldryn/aldryn-boilerplate-bootstrap3#180]
Now bootstrap 4 is officially in beta, bootstrap 3 is now becoming redundant. 

https://blog.getbootstrap.com/2017/08/10/bootstrap-4-beta/

Bootstrap 4 changes a lot of things and is not backwards compatible with bootstrap 3.

**Comment by AnselmeR** [comment]
Now bootstrap 4 is officially stable.

https://getbootstrap.com/

**Comment by vxsx** [comment]
Work in progress here: https://github.com/divio/djangocms-bootstrap4/
This package will stay with bootstrap3 only.
