### ISSUE TITLE
setStorage / getStorage

### ISSUE THREAD

**Issue by vxsx** [aldryn/aldryn-boilerplate-bootstrap3#70]
Currently we check for existence of `Storage`, but this check is incorrect and we should probably use Modernizr for that (and for all feature detects). 

Most common example - on mobile Safari in private browsing mode localstorage is disabled but the object still exists.

ref: https://github.com/Modernizr/Modernizr/blob/master/feature-detects/storage/localstorage.js

**Comment by vxsx** [comment]
we could look into https://github.com/doctyper/gulp-modernizr

**Comment by FinalAngel** [comment]
question is, if we want to use Modernizr in general within the boilerplate. The Storage issue will be fixed within: https://github.com/aldryn/aldryn-boilerplate-bootstrap3/pull/71

any opinions @Flight @darioalbanesi @yakky @Brankub @Lionardo @dhorelik @intellectronica ...

**Comment by darioalbanesi** [comment]
@vxsx what is incorrect about the check?

I found this [here](http://diveintohtml5.info/detect.html):
```javascript
function supports_local_storage() {
  try {
    return 'localStorage' in window && window['localStorage'] !== null;
  } catch(e){
    return false;
  }
}
```

I think Modernizr is a bit of an overkill if we only use it for this case. In general I think Modernizr is a great detection tool!

**Comment by FinalAngel** [comment]
@darioalbanesi this would be the correct behaviour: https://github.com/aldryn/aldryn-boilerplate-bootstrap3/pull/71/files#diff-244cd32e4f8793392e114aee260b246bR116

**Comment by vxsx** [comment]
i'm all for using modernizr, but not sure if boilerplate is a correct place to do it
if let's say we will provide some automated builder like gulp-modernizr then we'd have to make sure that it is actually run on the build step always, especially on aldryn, or state it very very very clearly that it's a user's responsibility, which is somewhat bad imo
