### ISSUE TITLE
add grid-float-breakpoint

### ISSUE THREAD

**Issue by Lionardo** [aldryn/aldryn-boilerplate-bootstrap3#72]
I would like to add this variable to the bootstrap settings file.
$grid-float-breakpoint

I encountered a lot of time the issue where I need to change it due to the fact that the navigation menu gets too long and breaks the header part of the page.

example:
>// Navbar collapse
//** Point at which the navbar becomes uncollapsed.
$grid-float-breakpoint:     $screen-md-min;
//** Point at which the navbar begins collapsing.
$grid-float-breakpoint-max: ($grid-float-breakpoint - 1);

**Comment by vxsx** [comment]
We switched to full bootstrap settings file a while ago https://github.com/aldryn/aldryn-boilerplate-bootstrap3/blob/master/private/sass/settings/_bootstrap.scss

**Comment by Lionardo** [comment]
ok, then we have an issue here because I'm using on a project the boilerplate 3.3.1 and it is not there.
