### ISSUE TITLE
Mixins need to be moved to libs or higher level

### ISSUE THREAD

**Issue by FinalAngel** [aldryn/aldryn-boilerplate-bootstrap3#74]
when moving to libsass we need to provide standard mixins and move ``layout/_mixins.scss`` accordingly.

the option is to use ``/libs`` or create a separate folder ``/mixins`` - open for discussion.

**Comment by Brankub** [comment]
As for me better is separate folder /mixins

**Comment by dhorelik** [comment]
`/mixins` folder makes more sense. Custom mixins will then be put in that folder as well, so that all mixings were in one place. `/libs` won't work like that.
