### ISSUE TITLE
gulp karma

### ISSUE THREAD

**Issue by vxsx** [aldryn/aldryn-boilerplate-bootstrap3#87]
I suggest changing `gulp karma` command to the `gulp tests:watch` or something similar and unrelated to actual implementation of the task. This would allow us to change implementation in a project level without renaming the task and thus being consistent everywhere.

**Comment by intellectronica** [comment]
+1

**Comment by FinalAngel** [comment]
will be fixed in https://github.com/aldryn/aldryn-boilerplate-bootstrap3/pull/88
